### ISSUE TITLE
Metadata

### ISSUE THREAD

**Issue by davedoesdev** [pulsejet/go-webauthn-js#1]
Great work on this! It'd be nice to have a maintained webauthn module available from Node.

Regarding removing net/http and loss of MDS - could you give more details why this breaks with GopherJS? Could we patch to use Node's http API?

Thanks again!

**Comment by pulsejet** [comment]
Hi @davedoesdev 

I have actually published a package at [go-webauthn-js](https://www.npmjs.com/package/go-webauthn-js), and have been using it in my staging setup with good results for a month or so. An example expressjs implementation [here](https://github.com/pulsejet/go-webauthn-js-server).

Actually, `net/http` doesn't break the module in any way; the reason I removed it is that it helps reduce the bundle size (as explained in the [blogpost](https://medium.com/@varunpp2/a-js-webauthn-server-running-in-the-browser-written-in-go-143f672ad085)). I am not using attestations, so didn't really care about this during development. Would be an added good to get it working though

**Comment by davedoesdev** [comment]
Hi @pulsejet 
Inspired by your work, I've made a Web Assembly version here: https://github.com/davedoesdev/webauthn4js
Let me know what you think. I've linked to go-webauthn-js in my README.

**Comment by pulsejet** [comment]
That is great! Thanks!

I originally did compile it with WebAssembly as GopherJS didn't play nicely with ugorji/go (see [the last section of this project's README](https://github.com/pulsejet/go-webauthn-js#wasm-target)), but gopherjs produced a leaner build in my testing. That said, I was using a pre-release Go 1.14 for WASM, so things might have changed now.
